#!/usr/bin/env python3
"""
AKIRA SASE - Secure Setup Script

This script helps initialize Akira with secure defaults.
"""

import os
import secrets
import sys
import subprocess
from pathlib import Path

def print_banner():
    """Print setup banner"""
    banner = """
    ╔══════════════════════════════════════════════════════════╗
    ║                                                          ║
    ║          🛡️⚔️  AKIRA SASE SETUP WIZARD  ⚔️🛡️           ║
    ║                                                          ║
    ║     Secure initialization for cybersecurity platform    ║
    ║                                                          ║
    ╚══════════════════════════════════════════════════════════╝
    """
    print(banner)

def generate_secure_key(length=32):
    """Generate a cryptographically secure random key"""
    return secrets.token_urlsafe(length)

def check_python_version():
    """Check if Python version is adequate"""
    print("\n[1/8] Checking Python version...")
    if sys.version_info < (3, 11):
        print(f"  ❌ Python 3.11+ required, found {sys.version_info.major}.{sys.version_info.minor}")
        return False
    print(f"  ✅ Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
    return True

def create_env_file():
    """Create .env file with secure defaults"""
    print("\n[2/8] Creating secure .env file...")

    if os.path.exists('.env'):
        response = input("  ⚠️  .env already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("  ⏭️  Skipping .env creation")
            return True

    # Generate secure keys
    jwt_secret = generate_secure_key(48)  # 64 chars
    api_secret = generate_secure_key(32)  # 43 chars

    # Get user input for required values
    print("\n  📝 Please provide the following information:")
    openai_key = input("    OpenAI API Key (or press Enter to set later): ").strip()
    firebase_project = input("    Firebase Project ID (or press Enter to set later): ").strip()

    env_content = f"""# Akira SASE - Environment Configuration
# Generated by setup.py on {__import__('datetime').datetime.now().isoformat()}

# ===================================
# OPENAI CONFIGURATION
# ===================================
OPENAI_API_KEY={openai_key or 'your-openai-api-key-here'}
OPENAI_MODEL=gpt-4
OPENAI_MAX_TOKENS=2000
OPENAI_TEMPERATURE=0.7

# ===================================
# FIREBASE CONFIGURATION
# ===================================
FIREBASE_PROJECT_ID={firebase_project or 'your-firebase-project-id'}
FIREBASE_CREDENTIALS_PATH=firebase-credentials.json

# ===================================
# API CONFIGURATION
# ===================================
API_HOST=0.0.0.0
API_PORT=8000
API_RELOAD=true

# ===================================
# SECURITY CONFIGURATION
# ===================================
# 🔐 AUTO-GENERATED SECURE KEYS - DO NOT SHARE!
API_SECRET_KEY={api_secret}
API_ACCESS_TOKEN=ak_{generate_secure_key(32)}

# JWT Configuration
JWT_SECRET_KEY={jwt_secret}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7

# ===================================
# LOGGING CONFIGURATION
# ===================================
LOG_LEVEL=INFO
LOG_TO_CONSOLE=true
LOG_TO_FILE=true
LOG_FILE_PATH=akira.log
LOG_MAX_SIZE_MB=100
LOG_BACKUP_COUNT=5

# ===================================
# ENVIRONMENT
# ===================================
ENVIRONMENT=development
DEBUG=true

# ===================================
# RATE LIMITING
# ===================================
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60
RATE_LIMIT_PER_HOUR=1000
RATE_LIMIT_SCAN_PER_HOUR=10

# ===================================
# SECURITY RESTRICTIONS
# ===================================
WHITELISTED_TARGETS=192.168.1.0/24,10.0.0.0/8,localhost,127.0.0.1
REQUIRE_TARGET_AUTHORIZATION=true
STRICT_SECURITY_MODE=true

# ===================================
# CORS CONFIGURATION
# ===================================
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
CORS_ALLOW_CREDENTIALS=true
CORS_MAX_AGE=600

# ===================================
# FEATURE FLAGS
# ===================================
ENABLE_OFFENSIVE_TOOLS=true
ENABLE_DEFENSIVE_TOOLS=true
ENABLE_AI_ANALYSIS=true
ENABLE_FIREBASE_LOGGING=true
"""

    with open('.env', 'w') as f:
        f.write(env_content)

    # Set restrictive permissions on .env
    os.chmod('.env', 0o600)

    print("  ✅ .env file created with secure keys")
    print("  🔒 File permissions set to 600 (owner read/write only)")
    return True

def check_dependencies():
    """Check if required system dependencies are installed"""
    print("\n[3/8] Checking system dependencies...")

    # Check for nmap
    try:
        result = subprocess.run(['nmap', '--version'],
                              capture_output=True,
                              timeout=5)
        print("  ✅ nmap installed")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        print("  ⚠️  nmap not found (optional but recommended)")
        print("      Install with: sudo apt install nmap (Linux) or brew install nmap (Mac)")

    return True

def install_python_dependencies():
    """Install Python dependencies"""
    print("\n[4/8] Installing Python dependencies...")

    try:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '--upgrade', 'pip'],
                      check=True)
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'],
                      check=True)
        print("  ✅ All Python dependencies installed")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ❌ Failed to install dependencies: {e}")
        return False

def create_firebase_template():
    """Create Firebase credentials template if not exists"""
    print("\n[5/8] Checking Firebase credentials...")

    if os.path.exists('firebase-credentials.json'):
        print("  ✅ firebase-credentials.json already exists")
        return True

    print("  ℹ️  firebase-credentials.json not found")
    print("     Please download from Firebase Console and save as firebase-credentials.json")
    print("     https://console.firebase.google.com/")
    return True

def create_directories():
    """Create necessary directories"""
    print("\n[6/8] Creating directories...")

    directories = ['logs', 'data', 'backups', 'temp']

    for directory in directories:
        Path(directory).mkdir(exist_ok=True)
        print(f"  ✅ Created {directory}/")

    # Create .gitkeep files to preserve empty directories in git
    for directory in directories:
        (Path(directory) / '.gitkeep').touch()

    return True

def verify_gitignore():
    """Verify .gitignore includes sensitive files"""
    print("\n[7/8] Verifying .gitignore...")

    if not os.path.exists('.gitignore'):
        print("  ❌ .gitignore not found!")
        return False

    with open('.gitignore', 'r') as f:
        content = f.read()

    required = ['.env', 'firebase-credentials.json', '*.log']
    missing = [item for item in required if item not in content]

    if missing:
        print(f"  ⚠️  Missing entries in .gitignore: {missing}")
        return False

    print("  ✅ .gitignore properly configured")
    return True

def create_admin_user():
    """Create initial admin user"""
    print("\n[8/8] Creating admin user...")

    print("  📝 Admin user will be created on first run")
    print("     Default credentials:")
    print("       Username: admin")
    print("       Password: (will be generated and displayed on first run)")
    print("     🔒 CHANGE PASSWORD IMMEDIATELY after first login!")

    return True

def print_next_steps():
    """Print next steps for user"""
    print("\n")
    print("╔══════════════════════════════════════════════════════════╗")
    print("║                                                          ║")
    print("║                  ✅ SETUP COMPLETE!                      ║")
    print("║                                                          ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print("\n📋 Next Steps:")
    print("\n1. Configure your credentials:")
    print("   - Edit .env and add your OpenAI API key")
    print("   - Download Firebase credentials to firebase-credentials.json")
    print("\n2. Review security settings:")
    print("   - Check WHITELISTED_TARGETS in .env")
    print("   - Review SECURITY.md for best practices")
    print("\n3. Start the server:")
    print("   python main.py")
    print("\n4. Access the API:")
    print("   http://localhost:8000/docs")
    print("\n5. Security reminders:")
    print("   ⚠️  NEVER commit .env or firebase-credentials.json")
    print("   ⚠️  Change default admin password on first login")
    print("   ⚠️  Use HTTPS in production")
    print("   ⚠️  Configure whitelisted targets before scanning")
    print("\n📖 Documentation:")
    print("   - Security: SECURITY.md")
    print("   - Deployment: DEPLOYMENT.md")
    print("   - README: README.md")
    print("\n")

def main():
    """Main setup function"""
    print_banner()

    steps = [
        ("Checking Python version", check_python_version),
        ("Creating .env file", create_env_file),
        ("Checking dependencies", check_dependencies),
        ("Installing packages", install_python_dependencies),
        ("Checking Firebase", create_firebase_template),
        ("Creating directories", create_directories),
        ("Verifying .gitignore", verify_gitignore),
        ("Creating admin user", create_admin_user),
    ]

    for step_name, step_func in steps:
        if not step_func():
            print(f"\n❌ Setup failed at: {step_name}")
            print("   Please fix the issues and run setup again.")
            sys.exit(1)

    print_next_steps()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed with error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
